### ISSUE TITLE
Seed generation algorithm synchronization

### ISSUE THREAD

**Issue by bartslinger** [peterwilli/iota-ledger-nano-s#2]
Hi Peter,

Good to see my work is being used for this. I'm still trying to find a nice solution to generate a deterministic seed from 24 words. Whatever we end up doing, we should try to use the same algorithm to make the wallets compatible. I see there is also some sort of node derivation in ledger. 

I'm currently deriving a node here: https://github.com/iota-trezor/trezor-mcu/blob/f3028dc0e681542cd5e1438caa89f67d520b4bff/firmware/fsm.c#L102

Then I use the private key and chain code combined to get a 64-byte 'seed'. That's converted to an IOTA seed here https://github.com/iota-trezor/trezor-mcu/blob/f3028dc0e681542cd5e1438caa89f67d520b4bff/firmware/iota.c#L76

This method is not definitive yet, depending on feedback I may still get.

**Comment by peterwilli** [comment]
Hi @bartslinger thanks for meeting up! I wouldn't be able to do it without you (or at least not as fast as I would)

I read on your blog (and git) that you also are going to try to use regular bip32 for seed generation. If we want to sync, we have to follow a path like that. The Ledger has much more strict security measures, one of them being no access to the seed (24 words) in plain text (i.e you **have** to use a derivation function)

So I think we'll have to move from there.

Ps: can you give me your wallet address? I want to transfer a part of my donations to you as your research helped me a lot, so this project is yours too.

**Comment by peterwilli** [comment]
@bartslinger I now see that you already moved to BIP32. I was confused by the use of the words '24 words' xD. For here on I'll refer to the actual ledger seed (24 words) as just 24 words to avoid confusion.

Can you give me a few test vectors on a random '24 words' you used?  This is so I can test it out to see if we are capable of generating the same seeds.

**Comment by managr** [comment]
Is there a way to reuse the https://github.com/bmavity/iota-seed-mnemonic
but wondering if seed generator has the access to the mnemonic or only private key which is generated from it.

**Comment by nglx** [comment]
Maybe that'll be helpful:
https://github.com/mlouielu/iota-mnemonic
There's a code that recovers seed from 24 words mnemonic. Could be also useful to restore the seed if ledger is lost or damaged.

**Comment by bartslinger** [comment]
@managr That's not compatible with the ledger I'm afraid. As far as I understand the ledger app does not have direct access to the mnemonic words.

**Comment by nglx** [comment]
Oh, I see, that makes perfect sense from security perspective...

**Comment by peterwilli** [comment]
@bartslinger is right. You can't access the direct seed (which is the entire point of the Ledger) unless you roll it through a derivation function (what we're doing)
