### ISSUE TITLE
Simplified version which only generates seed from Ledger

### ISSUE THREAD

**Issue by nglx** [peterwilli/iota-ledger-nano-s#5]
I really like the project but having in mind the complexity of the iota wallet implementation I was wondering if for a start we could implement something simpler.

Ledger Nano S could only generate the seed (based on the 24 words or the derived private key) and then the virtual keyboard is used to populate the seed in the desktop (light) wallet.

Password Manager app is a good place for a start with that - the virtual keyboard is already implemented - the only thing to implement is the custom password generator which generates password which is actually the IOTA seed:
https://github.com/LedgerHQ/blue-app-password-manager/blob/master/src/password_generation.c

Let me know your thought about it.

**Comment by RobinUS2** [comment]
The moment the seed (essentially the private key) leaves the ledger the purpose of having a hardware wallet is lost. The key should always remain inside (apart from the 24 word backup) and should be used to sign transactions and such where the data of the transaction is signed inside the ledger and only the result comes back.

**Comment by nglx** [comment]
@RobinUS2 have to agree, but anyway I would like to have something more secure than I have now. Closing.

**Comment by RobinUS2** [comment]
@managr fair point and the wallet definitely needs improvement. Something like an encrypted wallet with a password that encrypts/decrypts the seed would be a start and is not uncommon with many other wallets.

**Comment by peterwilli** [comment]
@RobinUS2 this is what the android IOTA wallet does too. Hey... Aren't you this carrot guy?
